### ISSUE TITLE
Square Pyramids are bugged

### ISSUE THREAD

**Issue by QuImUfu** [Phylogeny/ExtraBitManipulation#11]
Drawn Square Pyramids with direction other than up do not work correctly. The preview shows correctly but when releasing the button nothing happens.  
Drawn Square Pyramids with up direction do work correctly.  

Global Square Pyramids with any direction do work correctly. 

Local Square Pyramids with any direction do work in a very weird way. They only draw in the block "above"  (moved 1 block in the direction of the face you click at) the block you mark.

I'm using these Versions: 
1.10.2-2.3.2 ExtraBitManipulation
1.10.2-12.12 Chisels & Bits  
1.10.2-12.18.3.2185 Forge 
1.10.2-1.3.0 MCMultiPart

**Comment by Phylogeny** [comment]
As for all local shapes, they did not work when both in offset mode and local mode. As for drawn rectangular pyramids, they worked in positive axial directions, but not negative ones. They are both now fixed.
