### ISSUE TITLE
Is this just me?

### ISSUE THREAD

**Issue by RavenArcher** [Phylogeny/ExtraBitManipulation#19]
When I wear bit armor on my head, the armor doesn't move when my head does as seen in the pictures below.  Any ideas as to what is causing it to happen, or is this normal?
![2017-11-13_15 09 27](https://user-images.githubusercontent.com/33639482/32749490-226f1e14-c885-11e7-9658-e1143246181a.png)
![2017-11-13_15 09 34](https://user-images.githubusercontent.com/33639482/32749494-2578edba-c885-11e7-87fd-2b4bd280ce4f.png)

**Comment by RavenArcher** [comment]
Forgot to mention I'm playing 1.10.2, and that any chest pieces I make render smaller and inside my player model.

**Comment by Phylogeny** [comment]
I'm assuming this is another instance of incompatibility with More Player Models.

**Comment by Phylogeny** [comment]
This should be fixed as of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912). Let me know if you run into any problems.
