### ISSUE TITLE
[1.9] Capability is attached to every tile entity and item stack ever

### ISSUE THREAD

**Issue by asiekierka** [Phylogeny/ExtraBitManipulation#2]
This means every single object in world now has the additional load of having to store SculptSettings. You can debug this with Player's Sampler (in the FastCraft thread) and "/sampler blockinfo".

**Comment by Phylogeny** [comment]
Oh dear. You are quite right. I've failed to check if event.getObject() is an instance of EnitiyPlayer in the AttachCapabilitiesEvent method. I'll fix this shortly. Thanks.

**Comment by Phylogeny** [comment]
I see. AttachCapabilitiesEvent.Entity as well. Yes, your fix is the proper one.

**Comment by asiekierka** [comment]
Heh.

By the way, we found this while testing out mods for BetterThanMinecon - the in-game Minecraft modding convention! Since we will probably use your mod for building either way, you should consider signing up!

https://docs.google.com/forms/d/1KOwF636KDjuDBZtatTLhiG2rPIHQAgTHfzEy63AmwHg/viewform
