### ISSUE TITLE
Suggestion: Make Chiseled Armor not diamond

### ISSUE THREAD

**Issue by sleurk** [Phylogeny/ExtraBitManipulation#20]
When playing, I want to make a chiseled armor set, but I won't spend 24 diamonds to do it until much later in the game. Since the armor is added for cosmetic purposes, I think it should be easier to make and not give diamond-level protection.

**Comment by Phylogeny** [comment]
As of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912), both vanilla diamond and iron armor is chiselable.
