### ISSUE TITLE
MPM and Extra Bit manipulation

### ISSUE THREAD

**Issue by Greenjoe12345** [Phylogeny/ExtraBitManipulation#21]
The rendering of chiseled armor is kinda broken with more player models

the hat and arm and leg pieces do not properly move with those body parts

the armor is also too small when placed on the player, and has to be adjusted and moved to be in the right place

also, one more thing, the default diamond armor styled stuff seems to work, it moves with the head, but addding a custom chisled thing makes it not move with the head

**Comment by Greenjoe12345** [comment]
You added incompatibility, is this bug unfixable?

**Comment by Greenjoe12345** [comment]
So once it updates on curseforge it'll be fixed?

**Comment by Phylogeny** [comment]
I'm looking into adding one other mod integration right now, but yes, the next release will have this change. It should be fixed.

**Comment by Greenjoe12345** [comment]
Nice :) what other mod?

**Comment by Phylogeny** [comment]
CNPCs #17

**Comment by Greenjoe12345** [comment]
Looking forward to the update coming out :smile:

**Comment by Phylogeny** [comment]
Alright, well unexpectedly, making the static/default chiseled armor model render properly with MPM and CNPCs ended up being significantly harder than doing so for the custom chiseled armor items/blocks rendering in their own layer, but I believe I've got it now. I'll do more testing, but it does finally seem solid. It shouldn't be too much longer.

**Comment by Greenjoe12345** [comment]
Alright, Cool!

**Comment by Phylogeny** [comment]
This should be fixed as of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912). Let me know if you run into any problems.
