### ISSUE TITLE
Armor in Vanity slots not rendering for others in multiplayer

### ISSUE THREAD

**Issue by OfficialCFM** [Phylogeny/ExtraBitManipulation#22]
Hello.

In multiplayer, I've noticed that Chiseled Armor placed in a Vanity slot does not render for people other than the player wearing it.
![image](https://user-images.githubusercontent.com/29025387/37686447-e1828218-2c6d-11e8-81d5-62cafb63c10b.png)
Notice the hat is there in my view.

![](https://i.imgur.com/SeLX5yG.png)
This is the view my friend has, and the hat is missing.

Any way this can be fixed on our end?

**Comment by xAlicatt** [comment]
Was coming here to report this. Looks like it hasn't even been replied to yet...that's unfortunate.

**Comment by Phylogeny** [comment]
This is fixed as of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912).
