### ISSUE TITLE
Normal armour still renders when wearing custom armour in vanity slots

### ISSUE THREAD

**Issue by Aerolfos** [Phylogeny/ExtraBitManipulation#23]
See picture. Both the customized armour and chainmail helmet are rendering. It should be rather obvious that I do not want the normal helmet to render.

[Picture](https://i.imgur.com/7tzKf7m.png)

**Comment by Phylogeny** [comment]
As of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912), there are 4 sets of vanity armor. The first set renders in place of the player's main armor set, while the remaining 3 sets render in addition to it.

**Comment by MissPotato** [comment]
This seems to be happening again in 3.4.1, Chisel and Bits 14.30 and forge 2815. I rollbacked to the recommended forge version as well and it still happened.
