### ISSUE TITLE
Chiseled armor incompatibility with FoolCraft 3 mods.

### ISSUE THREAD

**Issue by storrico** [Phylogeny/ExtraBitManipulation#24]
Just that, i believe i did everything ok, 

the torso is redminesioned to be smaller and it appears at leg height

https://puu.sh/Ba0xa/8acaa75770.png

**Comment by Phylogeny** [comment]
I can confirm that the same incompatibility with More Player Models occurs in FoolCraft 3, even though MPM is not installed. I just did some basic testing with the current build, and it appears that some of the more general steps I took to support MPM also support whichever mod(s) are doing similar things in FC3.

The next EBM release should fix it.

scalda/Foolcraft_3#224

**Comment by Phylogeny** [comment]
This should be fixed as of [v3.3.0](https://minecraft.curseforge.com/projects/extra-bit-manipulation/files/2599912). Let me know if you run into any problems.
