### ISSUE TITLE
Can't see my Armor

### ISSUE THREAD

**Issue by XeramTheWerewolf** [Phylogeny/ExtraBitManipulation#25]
Hello, so installed this mod, used template to create my armor, made the armor, and put on myself, but I can't see it... Any help?

**Comment by Phylogeny** [comment]
Have you followed the steps described here: https://minecraft.curseforge.com/projects/extra-bit-manipulation/pages/chiseled-armor

**Comment by XeramTheWerewolf** [comment]
yes I did, and still nothing

**Comment by Phylogeny** [comment]
In that case:
1. Which EBM version are you using?
2. Which MC version are you using?
3. Which Forge version are you using?
4. Is this happening with chiseled blocks of bits from vanilla blocks or just certain mod blocks?
5. Does the item model render as expected in your inventory, or does it also render nothing?
6. Can you open the chiseled armor GUI while wearing the invisible armor? (If you can, please provide a screen shot.)

**Comment by Phylogeny** [comment]
I'll reopen this issue when/if you find the time to respond.
