### ISSUE TITLE
Suggestion: replace player model with chisel armor (vanish player model)

### ISSUE THREAD

**Issue by olegikoligik** [Phylogeny/ExtraBitManipulation#28]
Example:
![screenshot 167](https://user-images.githubusercontent.com/22132987/45569984-e651d680-b869-11e8-807a-4fb96bf2aae7.png)

**Comment by Phylogeny** [comment]
This is added in v3.4.0

The visibility of player model parts and overlays can be individually toggled in the Chiseled Armor GUI.
