### ISSUE TITLE
Suggestion: When creating new bit armor add a default model.

### ISSUE THREAD

**Issue by Edulml** [Phylogeny/ExtraBitManipulation#30]
I'm starting with the bit armor and I'm excited with the possibilities. However, even finding where is the front of the head was tricky. I'd really like a default bit arrangement that looks like the vanilla armor (maybe with a grey armor template block bit) so that using that part of the mod becomes much easier.

**Comment by Phylogeny** [comment]
When you say "finding the front of the head" are you referring to the in-world bodypart template that renders while in creation mode? If so, that's simply the blue texture.

And I'm not sure what you mean by "default bit arrangement". Chiseled armor should be empty by default.

**Comment by Edulml** [comment]
By "finding the front of the head" I meant the face. I don't know why I didn't just say face. Anyway, it's still tricky to know in which face of the template the armor will be in front unless I put different bits on each face and then try out the armor piece.

And by "default bit arrangement" I mean to have the same layout as the model of the armor you get by crafting an iron or diamond armor piece with a chisel. When starting out I'd really appreciate to have a familiar template to start out with before coming up with more detailed models. 

Thank you for your attention.

**Comment by Phylogeny** [comment]
I believe that the front of the bodypart model being the only side to render with color is straightforward enough.

And if you mean that chiseled armor would have blocks pre-loaded into them, then no; I don't want them to have to be cleared out every time one crafts them.

No problem.

**Comment by Edulml** [comment]
That was fast. Then what about adding it as an option? More expert builders can just ignore them and the learning curve will be much faster for those who are just starting out. Now I'm just spending time recreating the model that it's in the freshly crafted armor so I can know what goes where.
