### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by Rithsagea** [Phylogeny/ExtraBitManipulation#33]
Crash with the modpack Project Gear.
Using version 3.4.0 of ExtraBitManipulation

I tried launching the game 3 times in a row, and it crashed 3 times in a row. Not sure why.

https://paste.dimdev.org/wifafavoyo.mccrash
https://paste.dimdev.org/ilejemuqac.mccrash
https://paste.dimdev.org/osemofevul.mccrash

**Comment by Phylogeny** [comment]
Alright, the previous fix was just a bandaid, while this fix gets to the root of the problem and removes any potential for key binding NPEs.

**Comment by Phylogeny** [comment]
This is fixed in v3.4.1

**Comment by Rithsagea** [comment]
Thanks

I play on a mac, so if something can go wrong, it will.
