### ISSUE TITLE
Glowstone on chiseled armor

### ISSUE THREAD

**Issue by sverinn** [Phylogeny/ExtraBitManipulation#34]
When added to chiseled armor, glowstone blocks do not emit any light, though it is glowing on the puppet. Is it intended / a bug / not implemented yet?

**Comment by Phylogeny** [comment]
If you mean emitting actual light in the world, no that will not happen. If you simply mean rendering the quads emissively, then that will only occur if the chiseled block item model supports it. I simply render the chiseled block item model.
