### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by MysticAura** [Phylogeny/ExtraBitManipulation#5]
Update to 1.10.2 or if it's already fully compatible, let it show on curse for compatible versions.

**Comment by Entoarox** [comment]
It works in 1.10 as long as you don't actuallyt try to use the items, cause then you crash XD

**Comment by RobertLSnead** [comment]
This mod is not currently compatible for 1.10, loads but I get some opengl errors in chat window, all black and very glitchy.  Please update!

**Comment by Phylogeny** [comment]
I apologize for being so lazy for so long. I've finally ported to 1.10.2.
