### ISSUE TITLE
[Feature Request] Add Radial Support for EBM

### ISSUE THREAD

**Issue by edenprojectde** [Phylogeny/ExtraBitManipulation#6]
I dont have a working mousewheel and i really never preffered using it tbh so my feature request is that i can either config keys to add/sub to the size of the tools or that an radial option is available.

**Comment by Phylogeny** [comment]
I'll try to get this into the next update; if not, then certainly the one after that. I'll use the C&B radial key bind to open a similar GUI that will allow the setting of all bit tool data. Sculpting semidiameter and wall thickness will likely be set with sliders.

**Comment by Phylogeny** [comment]
I'm maybe half done with it now. It will definitely be in the next update.

**Comment by Phylogeny** [comment]
v2.2.0 implements this as described above, and has just been released for MC 1.8.9, 1.9.4, and 1.10.2
