### ISSUE TITLE
crash when pressing ANY key

### ISSUE THREAD

**Issue by redgoblin88** [Phylogeny/ExtraBitManipulation#8]
upon joining my friends server, i wait a few seconds to get the sync and let the world load.
after i have joined for a few seconds i then press "w" to move forward and crash...
i have changed my keybind for the radial menu to "button 3" (as my mouse has 2 extra buttons) and have noticed that 2.3.1 "fixed bug where pressing C&B radial menu key would crash if cound to non-standard key" HOWEVER as i said, my radial menu is button 3, NOT "w" which abnormal to what you says is fixed.

crashlog:
http://pastebin.com/tpz9s60L

**Comment by Phylogeny** [comment]
The problem is that you're using v2.2.1, rather than v2.3.1 (line 144 of the pastebin).

BTW, the reason it crashes in v2.2.1 when pressing any key is because the unsafe check of Keyboard#isKeyDown is performed every time InputEvent#KeyInputEvent is fired.
